### ISSUE TITLE
PayPal Express reports IPN verification failure

### ISSUE THREAD

**Issue by dxdc** [ingenesis/shopp#3604]
I'm having two issues with the current PayPal Express plugin (paid), I'm running Shopp 1.3.12dev (nearly identical branch to 1.3.11):

1. IPN verification fails. Upon comparison to the PayPal Standard plugin, the verify IPN code was different. Updating it to match the PayPal Standard format (i.e., see below) seemed to help, but I still get IPN verification errors. I double-checked the URL endpoints listed in the PayPal Standard file and they seem OK:

```
    public function verifyipn () {
        if ( Shopp::str_true( $this->settings['testmode'] ) ) return true;

        $_ = array();
        $_['cmd'] = '_notify-validate';

        $message = $this->encode( array_merge($_POST, $_ ) );
        $response = $this->send( $message );

        shopp_debug( 'PayPal IPN validation response: ' . var_export( $response, true ) );

        return ( 'VERIFIED' == $response );
    }
```

PayPal IPN response below. Without making the above change, this entire sequence below was completely empty, so I think I'm making progress... I haven't tested manually posting the sequence to the endpoint via curl yet to ensure at least the message is being assembled correctly.

```
[01-Oct-2016 15:15:45 UTC] Shopp: PayPal IPN validation response: stdClass::__set_state(array(
   'debuglog' => '',
   'ack' => 'Failure',
   'errorcode' => 
  array (
    0 => '81002',
  ),
   'shortmessage' => 
  array (
    0 => 'Unspecified Method',
  ),
   'longmessage' => 
  array (
    0 => 'Method Specified is not Supported',
  ),
   'severitycode' => 
  array (
    0 => 'Error',
  ),
))
```

2. Even when IPN failure occurs, the order still goes through. This is a big security flaw. Seems this was flagged in another place:

https://github.com/ingenesis/shopp/issues/3338

Any thoughts on how to fix this?

Thanks,
Dan

**Comment by crunnells** [comment]
@dxdc Can you post the request that is being sent to PayPal? Seems like there's something missing to trigger this error, which isn't well documented by PayPal. 

FYI, there was an earlier issue that is similar to this one, #2005 which was resolved back in 2013. Might be worth checking that the data going back to PayPal in the response is good.

**Comment by dxdc** [comment]
@crunnells thanks for your reply. Looking into this further, I think the IPN endpoint in PayPal express is wrong.

It's using `https://api-3t.paypal.com/nvp` but I think it actually should be `https://ipnpb.paypal.com/cgi-bin/webscr`.

Also, another mistake in the code (and, a mistake in the PayPalStandard.php file):

```
...
$_['cmd'] = '_notify-validate';
$message = $this->encode( array_merge( $_POST, $_ ) );
```

Based on the PayPal documentation, this is wrong. The 'cmd' var should be prepended, i.e.:

```
$message = $this->encode( array_merge( $_, $_POST ) );
```

Made some modifications to PayPalExpress.php, am testing those now.

**Comment by dxdc** [comment]
This is helpful too:

https://github.com/paypal/ipn-code-samples/tree/master/php

**Comment by dxdc** [comment]
This is also a nice script to run to test compatibility for PayPal HTTPS endpoint and TLS upgrades. Make sure ca-certificates are installed on your system (e.g., `sudo apt-get install ca-certificates`).

```
<?php

$ch = curl_init(); 

curl_setopt($ch, CURLOPT_URL, "https://tlstest.paypal.com/"); 
curl_exec($ch);
echo "\n";

if ($err = curl_error($ch)) {
	var_dump($err);
	echo "DEBUG INFORMATION:\n###########\n";
	echo "CURL VERSION:\n";
	echo json_encode(curl_version(), JSON_PRETTY_PRINT);
}

?>
```

**Comment by dxdc** [comment]
@crunnells @sierrab123 I think I've solved the problem; IPN was not correctly implemented in the PayPalExpress module at all (I think?? I can't even find reference to the use of the correct endpoints within the module, e.g.

```
Send response messages back to PayPal:

https://ipnpb.sandbox.paypal.com/cgi-bin/webscr (for Sandbox IPNs)
https://ipnpb.paypal.com/cgi-bin/webscr (for live IPNs)
```

I've corrected/updated the code for my copy, including cleaning up some functions that have been deprecated.

This still doesn't solve the fraud issue, ie.
https://github.com/ingenesis/shopp/issues/3338

But, it takes care of the verification one.

**Comment by crunnells** [comment]
I'm certain that PPE was working correctly initially. I'm surprised that the "old" IPN URL doesn't work for PPE, as it works fine for PPS. From what I understand, IPN responses are fairly general, regardless of what kind of PayPal transaction you're validating. There's nothing in the docs that say you should use one URL for PPS, and another for PPE. 

But, if it works, it works. Can you send me your changes so I can review them?

**Comment by dxdc** [comment]
@crunnells PayPal Express was set up to validate through these URL's

```
	public $sandboxapi = 'https://api-3t.sandbox.paypal.com/nvp';
	public $liveapi = 'https://api-3t.paypal.com/nvp';
```

I can't find any mention of these being successful IPN endpoints for PayPal though. You're certain it was working before?

I'll PM you on Slack regarding changes.

**Comment by sierrab123** [comment]
On another install that is getting inconsistent returns (I have purchased with no issue)

`REQUEST TO PAYPAL:
Array
(
    [USER] => xxxx
    [PWD] => xxx
    [SIGNATURE] => xxxx
    [VERSION] => 84.0
    [METHOD] => SetExpressCheckout
    [PAYMENTREQUEST_0_PAYMENTACTION] => Sale
    [LANDINGPAGE] => Billing
    [RETURNURL] => https://www.fernstudium-guide.de/online-kurse/confirm-order/?rmtpay=process
    [CANCELURL] => https://www.fernstudium-guide.de/online-kurse/warenkorb/
    [EMAIL] => Removed for git hub)
    [SHIPTOPHONENUM] => 
    [NOSHIPPING] => 1
    [L_PAYMENTREQUEST_0_NAME0] => Klausurlösungen Haushaltstheorie (KE2) FU Hagen
    [L_PAYMENTREQUEST_0_AMT0] => 6.90
    [L_PAYMENTREQUEST_0_NUMBER0] => 0
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [PAYMENTREQUEST_0_CURRENCYCODE] => EUR
    [PAYMENTREQUEST_0_ITEMAMT] => 6.90
    [PAYMENTREQUEST_0_TAXAMT] => 1.10
    [PAYMENTREQUEST_0_AMT] => 6.90
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
)

RESPONSE FROM PAYPAL:
stdClass Object
(
    [debuglog] => 
    [timestamp] => 2016-10-23T06:24:50Z
    [correlationid] => 115f130e20f6f
    [ack] => Failure
    [version] => 84.0
    [build] => 26106709
    [errorcode] => Array
        (
            [0] => 10413
        )

    [shortmessage] => Array
        (
            [0] => Transaction refused because of an invalid argument. See additional error messages for details.
        )

    [longmessage] => Array
        (
            [0] => The totals of the cart item amounts do not match order amounts.
        )

    [severitycode] => Array
        (
            [0] => Error
        )

)`

**Comment by dxdc** [comment]
Yep. The purchases all go through, but IPN failed. The IPN code is not correct, this is what's causing the failure.

**Comment by crunnells** [comment]
@sierrab123 Looks like the problem is that the item amount + tax amount is greater than the total. I'm guessing this is an inclusive tax issue.

@dxdc We'll need to see some error logs like Steve posted in order to further diagnose the issue.
